import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import { OhVueIcon, addIcons } from 'oh-vue-icons'
import router from '@/router'
import { createPinia } from 'pinia'
import { LaFileContractSolid } from "oh-vue-icons/icons";
import {
	FaExclamationTriangle,
	FaSyncAlt,
	FaSave,
	FaTimesCircle,
	FaRegularEye,
	FaRegularEyeSlash,
	FaHome,
	FaWhatsapp,
	FaPaperclip,
	FaPlug,
	FaUserAlt,
	FaBuilding,
	FaAddressBook,
	FaSignOutAlt,
	FaLock,
	FaBars,
	FaArrowUp,
	FaArrowDown,
	FaPlus,
	FaFilter,
	FaPlusCircle,
	FaPen,
	FaCheckCircle,
	FaCheck,
	FaWindowClose,
	FaBook,
	FaFileImage,
	FaAngleDown,
	FaSort,
	FaCircle,
	FaPhoneAlt,
	FaTrashAlt,
	FaCircleNotch,
	FaRegularSadCry,
	FaEdit,
	FaArrowRight,
	FaArrowLeft,
	FaChevronRight,
	FaChevronLeft,
	FaRegularFileImage,
	FaCogs,
	FaRegularCalendarAlt,
	FaSync,
	FaShareSquare,
	FaDownload,
	FaMapPin
} from 'oh-vue-icons/icons/fa/index.js'

import {
	BiGraphUpArrow,
	BiThreeDots,
	BiGear,
	BiEmojiSmileFill,
	BiCashCoin,
	BiStopwatch,
	BiArrowUpSquareFill,
	BiFileEarmarkFont,
	BiX,
	BiCheck,
	BiCalendarFill,
	BiBookmarkPlusFill,
	BiCircleFill,
	BiXSquare,
	BiCheckSquare,
	BiArrowLeftRight,
	BiWhatsapp
} from 'oh-vue-icons/icons/bi/index.js'

import { MdCancel, MdPendingactions,MdRefresh  } from 'oh-vue-icons/icons/md/index.js'

addIcons(
	FaExclamationTriangle,
	FaSyncAlt,
	FaSave,
	FaTimesCircle,
	FaRegularEye,
	FaRegularEyeSlash,
	FaHome,
	FaWhatsapp,
	FaPaperclip,
	FaPlug,
	FaUserAlt,
	FaBuilding,
	BiGraphUpArrow,
	FaAddressBook,
	FaSignOutAlt,
	FaLock,
	FaBars,
	FaPlus,
	BiThreeDots,
	FaFilter,
	FaPlusCircle,
	FaPen,
	FaCheckCircle,
	BiGear,
	FaWindowClose,
	FaBook,
	FaFileImage,
	BiEmojiSmileFill,
	FaAngleDown,
	BiCashCoin,
	FaArrowUp,
	FaArrowDown,
	FaSort,
	MdCancel,
	MdPendingactions,
	BiStopwatch,
	FaCircle,
	BiArrowUpSquareFill,
	FaPhoneAlt,
	FaTrashAlt,
	BiFileEarmarkFont,
	FaCircleNotch,
	FaRegularSadCry,
	FaEdit,
	FaArrowRight,
	FaArrowLeft,
	FaChevronRight,
	FaChevronLeft,
	FaCheck,
	BiX,
	BiCheck,
	FaRegularFileImage,
	BiCalendarFill,
	FaCogs,
	FaRegularCalendarAlt,
	BiBookmarkPlusFill,
	BiCircleFill,
	BiXSquare,
	BiCheckSquare,
	FaSync,
	FaShareSquare,
	FaDownload,
	FaMapPin,
	BiArrowLeftRight,
	BiWhatsapp,
	MdRefresh,
  LaFileContractSolid
)


const app = createApp(App).component('VIcon', OhVueIcon)

app.use(createPinia())
app.use(router)

app.mount('#app')